config/routes.rb
Rails.application.routes.draw do
  resources :scaffold_tests
  # get '/scaffold_tests', to: 'scaffold_tests#index'
  get 'cards/create'
  get 'cards/update'
  get 'cards/destroy'
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
    
  mount RailsAdmin::Engine, at: '/dashboard/admin', as: 'rails_admin'
  match "/dashboard/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  get '/', to: 'pages#top'
  get '/regions', to: 'pages#regions'
  get '/contests', to: 'pages#contests'
  get '/participants', to: 'pages#participations'
  get '/users', to: 'pages#users'
  get '/observations/more', to: 'pages#get_more'
  get '/contests/more', to: 'pages#get_more_contests'

  get '/contest/:slug', to: 'pages#contest'
  get '/:region_slug/:contest_slug', to: 'pages#region_contest'
  get '/:slug', to: 'pages#region'
  get '/region/:slug/bioscore', to: 'pages#region_bioscore'
  get '/regions/search/species', to: 'pages#search_species'
  post '/regions/search/species', to: 'pages#search_species'
  get '/regions/search/sightings_count', to: 'pages#sightings_count'

  namespace :api do
    namespace :v1 do
      post '/user', to: 'user#create'
      put '/user', to: 'user#update'
      delete '/user', to: 'user#close_account'
      post '/user/login', to: 'user#login'
      post '/user/logout', to: 'user#logout'
      
      post '/contest', to: 'contest#create'
      put '/contest', to: 'contest#update'
      delete '/contest', to: 'contest#destroy'
      get 'contests', to: 'contest#list'
      get 'contest/data/', to: 'contest#data'
      get '/contest/:contest_id/regions', to: 'participation#search'
      get '/contest/:contest_id/regions/:region_id/observations', to: 'observation#search'
      get '/contest/:contest_id/top_species', to: 'observation#top_species'
      get '/contest/:contest_id/top_people', to: 'observation#top_people'
      get '/contest/:contest_id/observations', to: 'observation#search'

      post '/participation', to: 'participation#create'
      put '/participation', to: 'participation#update'
      delete '/participation', to: 'participation#destroy'    
      get '/participation/:contest_id/:region_id/top_species', to: 'observation#top_species'
      get '/participation/:contest_id/:region_id/top_people', to: 'observation#top_people'
      get '/participation/:contest_id/:region_id/undiscovered_species', to: 'observation#undiscovered_species'

      post '/region', to: 'region#create'
      get '/region/:region_id', to: 'region#show'
      put '/region/:id', to: 'region#update'
      patch '/region/:id', to: 'region#update'
      delete '/region/:id', to: 'region#destroy'
      get '/regions', to: 'region#search'
      get '/region/:region_id/undiscovered_species', to: 'observation#undiscovered_species'
      get '/region/:region_id/top_species', to: 'observation#top_species'
      get '/region/:region_id/top_people', to: 'observation#top_people'
      get '/region/:region_id/observations', to: 'observation#search'
      get '/regions/search/species', to: 'region#search_by_species'
      get '/region/:region_id/sightings_count', to: 'region#sightings_count'
      get '/region/:region_id/species_image', to: 'region#species_image'

      get '/region/polygons', to: 'region#polygons'
      get '/region/polygon/generate', to: 'region#generate_polygon'
      get '/region/data/:region_id/:contest_id', to: 'region#data'

      post '/observations', to: 'observation#bulk_create'
      get '/observations/more', to: 'observation#get_more'
      get '/observations/total_counts', to: 'observation#get_total_counts'
      get '/observations/for_questa/closest', to: 'observation#get_closest_sightings'
      get '/observations/for_questa/:id', to: 'observation#get_observation_for_questa'

      get '/observations/contest_region', to: 'observation#contest_region'
      get '/observations/region/:id', to: 'observation#region'
      get '/observations/participation/:id', to: 'observation#participation'
      get '/observations/contest/:id', to: 'observation#contest'
      get '/observations/:id', to: 'observation#data'
      get '/observations/species/autocomplete', to: 'observation#get_species'

    end
  end

  get "*path", to: redirect('/')

end

app/views/pages/_contest_top_page.html.erb
<% if c.starts_at < Time.now && c.ends_at > Time.now %>
<div class="row mt-5 contest">
<% else %>
<div class="row mt-5">
<% end %>
  <div class="col">
  	<div class="row">
  		<div class="col h4 d-flex justify-content-center"><a href="<%= c.get_path %>" class="contest-title-link"><%= c.title %></a></div>
    </div>
  	<div class="row mt-3">
  		<div class="col d-flex justify-content-center fw-bold h6">For observations made between <%= c.starts_at.strftime '%Y/%m/%d' %> and <%= c.ends_at.strftime '%Y/%m/%d' %></div>
    </div>
  	<div class="row mb-3">
  		<div class="col d-flex justify-content-center fs-italic h6">Submissions accepted up to <%= c.last_submission_accepted_at.strftime '%Y/%m/%d' %></div>
    </div>
  </div>
</div>
<div class="row my-3 d-flex justify-content-center">
	<div class="col-10 d-flex justify-content-center"><%= c.description&.html_safe || '' %></div>
</div>

<% if c.starts_at>Time.now %>
  <div class="row my-3">
  	<div class="col d-flex justify-content-center fw-bold countdown" data-starts-at="<%= c.starts_at %>" data-id="<%= c.id %>" id="countdown-<%= c.id %>">
    </div>		
  </div>
	<script>	

</script>
<% end %>

<% if c.starts_at<Time.now %>
	<%= render partial: 'statistics', locals: { object: observations_object } %>
<% end %>

app/views/pages/_ongoing_contests.html.erb
<script>
  <% if show_more_contests == false %>
    $('.show_more_contests').hide();
  <% end %>
</script>
<% contests.each.with_index(1) do |c,i| %>
  <%= render partial: 'contest_top_page', locals: { c: c, i: i, observations_object: c, show_more_link: false } %>
<% end %>

app/views/pages/_participation_form.html.erb
<% modalid = participation.nil? ? 'new' : participation.id %>

<div class="modal fade participation-modal participation-modal-<%= modalid %>" tabindex="-1" id="<%= id %>" data-id="<%= modalid %>">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title fw-heavy"><%= title %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <% if @user.admin? %>
          <div class="row justify-content-center mb-5">
            <div class="col-6 col-lg-4">
              <div class="input-group">
                <select class="form-select status_participation">
                  <% if participation.nil? %>
                    <option value="submitted" selected disabled>submitted</option>
                  <% else %>    
                    <option value="<%= participation.status %>" selected><%= participation.status %></option>
                     <% if @user.admin? %>
                      <option value="refused" <%= participation.refused? ? 'selected' : '' %>>refuse</option>
                      <option value="removed_by_admin" <%= participation.removed_by_admin? ? 'selected' : '' %>>remove</option>
                    <% else %>
                      <% if participation.submitted? || participation.accepted? %>   
                        <option value="removed_by_region" <%= participation.removed_by_region? || participation.removed_by_admin? ? 'selected' : '' %>>remove</option>
                      <% end %> 
                    <% end %>
                  <% end %>  
                </select>
              </div>
            </div>
          </div>
        <% end %>

        <div class="row">
          <div class="col-12 col-lg-6">
            <label class="form-label">My Regions</label>
            <div class="input-group">
              <select class="form-select region_id_participation">
                <% regions = @user.admin? ? Region.all : @user.regions %>
                <% regions.each do |r| %>
                  <option value="<%= r.id %>" <%= participation && participation.region_id==r.id ? 'selected' : '' %>><%= r.name %></option>
                <% end %>
              </select>
            </div>
          </div>
          <div class="col-12 col-lg-6">
            <label class="form-label">Select a Contest</label>
            <div class="input-group">
              <select class="form-select contest_id_participation">
                <% Contest.where(status: Contest.statuses[:online]).each do |c| %>
                  <option value="<%= c.id %>" <%= participation && participation.contest_id==c.id ? 'selected' : '' %>><a href="/contest/<%= c.id %>"><%= c.title %></a></option>
                <% end %>
              </select>
            </div>
          </div>
        </div>
          
        <div class="row mt-5">  
          <div class="col">
            <div class="input-group">
              <% DataSource.all.each do |ds| %>
                <div class="form-check form-check-inline">
                  <input class="form-check-input data-source-<%= modalid %>" type="checkbox" name="data-sources-<%= modalid %>" id="data-source-<%= modalid %>-<%= ds.id %>" <%= participation && participation.data_sources.pluck(:id).include?(ds.id) ? 'checked' : '' %> value="<%= ds.id %>">
                  <label class="form-check-label" for="data-source-<%= modalid %>-<%= ds.id %>"><%= ds.name %></label>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="row justify-content-center my-5">
          <div class="col-8">
            <div class="form-group">
              <button class="btn btn-outline-secondary w-100 participation_save_action" data-id="<%= participation.nil? ? 'new' : participation.id %>">Save</button>
            </div>
          </div>
        </div>
        <div class="row justify-content-center mb-3">
          <div class="col-8 validation-messages">
            <span class="text-danger validation-ok organization_name">Title is required.</span>
            <span class="text-danger validation-ok email">Start date and time is required.</span>
            <span class="text-danger validation-ok email">End date and time is required.</span>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/_polygon.html.erb
<div class="row polygon-json">
  <div class="col">
    <div class="input-group mb-3">
      <span class="input-group-text polygon-colour">Polygon: </span>
      <input type="text" class="form-control" placeholder="Enter Polygon GeoJson" value="<%= p.nil? ? '' : p %>" <%= p.nil? ? '' : 'readonly' %>>
      <button class="btn btn-outline-secondary polygon-draw" type="button">Draw</button>
      <button class="btn btn-outline-secondary polygon-remove" type="button" <%= remove_button_disabled ? 'disabled' : '' %>>Remove</button>
    </div>
  </div>  
</div>

app/views/pages/_ranked_observer.html.erb
<div class="row mb-3 justify-content-center">
  <div class="col-2 fw-bold"><%= i %>.</div>
   <div class="col-6"><span><%= object[0] %></span></div>
  <div class="col-4 d-flex justify-content-end"><%= number_with_delimiter object[1], delimiter: ',' %></div>
</div>

app/views/pages/_region_top_page.html.erb
<div class="row mt-5">
  <div class="col-3">
    <img src="<%= r.logo_image_url.nil? ? r.logo_image : r.logo_image_url %>" class="img-fluid" style="width:35px;" loading="lazy">
  </div>
  <div class="col-7">
    <div class="row">
      <div class="col h4"><%= r.name %></div>
    </div>
  </div>
  <div class="col-2 d-flex justify-content-end">
    <a href="<%= r.get_path %>" class="region-title-link">View</a>
	</div>
</div>

app/views/pages/_region_with_species_count.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script>

    function set_cookie(q, pathname) {
        clear_search_cookie();
        Cookies.set("pathname", pathname);
        Cookies.set("q", q);
        theCookies = document.cookie.split(';');
    }

    function theFunction (obj) {
      var id = obj.id;
      var r_id = id.match(/^[\d]+/);
      $('#' + id).hide();

      $('#' + r_id + "_description").css({
        // "white-space": "normal",
        // "overflow" : "visible"
        "cursor": "pointer",
        "height": "200px",
        "white-space": "initial",
        "transition": "height 0.2s ease-in-out"
      });
    }
    if (document.getElementsByClassName("tooltip-pr")) {
      var divs = document.getElementsByClassName("tooltip-pr");
      for (var i=0; i < divs.length; i++) {
        divs[i].addEventListener("mouseover", autoOver);
        divs[i].addEventListener("mouseout", autoOut);
      }
    }
    function autoOver() {
      this.style.height = this.scrollHeight + "px";
      this.style.paddingLeft = "calc(var(--bs-gutter-x) * .5)";
      this.style.display = 'inline';
    }
    function autoOut() {
      this.style.removeProperty('height');
      this.style.display = "-webkit-box";
      this.style.paddingLeft = "calc(var(--bs-gutter-x) * .5)";
    }

    $(document).ready(function() {
      $.ajax({
        url: "/api/v1/region/<%= r.id %>/sightings_count",
        data: { month_filter: "<%= month_filter&.html_safe %>",
                year_filter: "<%= year_filter&.html_safe %>",
                search_text: "<%= search_text&.html_safe %>" },
        cache: false,
        dataType: 'json',
        success: function(data){
            text = data.property_sightings_count
            if (text == 0) {
              text = 'Be first to find!';
            }
            $("#<%= r.id %>_property_sightings").text(text);
            $("#<%= r.id %>_locality_sightings").text(data.locality_sightings_count);
            $("#<%= r.id %>_gr_sightings").text(data.greater_region_sightings_count);
            $("#<%= r.id %>_total_sightings").text(data.total_sightings_count);
        } 
      });
    });

  </script>

  <div class="row mb-5" id="searched_region" >

  <% if search_text.present? %>
    <div class="col-2 flex-nowrap flex-shrink-1 align-self-center text-center" style="padding: 1 0 0 0;">
      <% species_image_url = RegionsObservationsMatview.get_species_image(region_id: r.id, search_text: search_text) %>
      <% if species_image_url.present? %>
        <a href="<%= species_image_url %>" target="_blank">
          <img src="<%= species_image_url %>" style="height:150px;width:90%;object-fit:cover;">
        </a>
      <% end %>
    </div>
  <% else %>
    <div class="col-2 flex-nowrap flex-shrink-1 align-self-center text-center" style="padding: 1 0 0 0;">
      <% if r.logo_image_url || r.logo_image %>
        <% if r.region_url %>
          <a href="<%= r.region_url %>" target="_blank">
            <img src="<%= r.logo_image_url ? r.logo_image_url : r.logo_image %>" style="height:150px;width:90%;object-fit:contain;">
          </a>
        <% else %>
          <img src="<%= r.logo_image_url ? r.logo_image_url : r.logo_image %>" style="height:150px;width:90%;object-fit:contain;">
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="col-3 flex-nowrap flex-shrink-1" style="padding: 1 0 0 0; " >
    <% if search_text.present? %>
      <div class="row mt-2">
        <div class="col-5" style="padding-right:1px;">
          <% if r.logo_image_url || r.logo_image %>
            <% if r.region_url %>
              <a href="<%= r.region_url %>" target="_blank">
                <img src="<%= r.logo_image_url ? r.logo_image_url : r.logo_image %>" class="float-start" style="height:75px;width:100%;object-fit:contain;">
              </a>
            <% else %>
              <img src="<%= r.logo_image_url ? r.logo_image_url : r.logo_image %>" class="float-start" style="height:75px;width:100%;object-fit:contain;">
            <% end %>
          <% end %>
        </div>
        <div class="col-7 h5 blue-font fw-bold header-col" style="padding-left:10px;">
          <a href="<%= r.get_path %>" class="region-link" onclick="set_cookie('<%= search_text %>', '<%= r.get_path %>');" target="_blank">
            <%= r.name&.html_safe %>
          </a>
        </div>
      </div>
    <% else %>
      <div class="row mt-2 h5 blue-font fw-bold header-col" style="padding-left:10px;">
        <a href="<%= r.get_path %>" class="region-link" target="_blank">
          <%= r.name&.html_safe %>
        </a>
      </div>
    <% end %>
    <div class="row mt-1 h6 fw-bold yellow-font tooltip-pr" id="<%= r.id %>_description">
      <%= r.description&.html_safe || '' %>
    </div>
    <%
=begin%>
 <a class="more-content" href="#" id="<%= r.id %>_more_link" onclick="theFunction(this);" >
      ...(more)
    </a>
<%
=end%>
  </div>
  <% if search_text.present? %>
    <div class="col-2 flex-nowrap flex-shrink-1 align-self-center text-center fw-bold h3 blue-font" style="padding: 1 0 0 0; " id="<%= r.id %>_total_sightings" >
    </div>
  <% else %>
    <div class="col-2 flex-nowrap flex-shrink-1 align-self-center text-center h6 blue-font" style="padding: 1 0 0 0; " id="<%= r.id %>_total_sightings" >
    </div>
  <% end %>
  <div class="col-1 flex-nowrap flex-shrink-1 align-self-center text-center h6 blue-font" style="padding: 1 0 0 0" id="<%= r.id %>_property_sightings" >
  </div>
  <div class="col-2 flex-nowrap flex-shrink-1 align-self-center text-center h6 blue-font" style="padding: 1 0 0 0" id="<%= r.id %>_locality_sightings" >
  </div>
  <div class="col-1 flex-nowrap flex-shrink-1 align-self-center text-center h6 blue-font" style="padding: 1 0 0 0;" id="<%= r.id %>_gr_sightings" >
  </div>
  <% if search_text.present? %>
    <div class="col-1 flex-nowrap flex-shrink-1 align-self-center text-center h6 blue-font" style="padding: 1 0 0 0;" id="<%= r.id %>_bioscore">
      <%= r.bioscore %>
    </div>
  <% else %>
    <div class="col-1 flex-nowrap flex-shrink-1 align-self-center text-center fw-bold h3 blue-font" style="padding: 1 0 0 0;" id="<%= r.id %>_bioscore">
      <%= r.bioscore %>
    </div>
  <% end %>
</div>

app/views/pages/_signup_modal.html.erb
<div class="modal fade signup-modal" tabindex="-1" id="<%= id %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">        
        <h4 class="modal-title fw-heavy"><%= title %></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center mt-5 mb-3">
          <div class="col-8">
            <div class="form-group">
              <input type="text" class="form-control organization_name" placeholder="Organization Name" required="required">
            </div>
          </div>
        </div>  
        <div class="row justify-content-center mb-3">
          <div class="col-8">
            <div class="form-group">
              <input type="email" class="form-control email" placeholder="Email" required="required">
            </div>
          </div>
        </div>          
        <div class="row justify-content-center mb-3">
          <div class="col-8">
            <div class="form-group">
              <input type="password" class="form-control password" placeholder="Password" required="required">
            </div>
          </div>    
        </div>
        <div class="row justify-content-center mb-5">
          <div class="col-8">            
            <div class="form-group">
              <button class="btn btn-outline-secondary w-100" id="<%= id %>_action" disabled><%= button_text %></button>
            </div>
          </div>
        </div>    
        <div class="row justify-content-center mb-3">
          <div class="col-8 validation-messages">            
            <span class="text-danger validation-ok organization_name_unique">Organization name is already taken.</span>
            <span class="text-danger validation-ok email_unique">Email is already taken.</span>
            <span class="text-danger validation-ok organization_name_v">Organization name is required.</span>
            <span class="text-danger validation-ok email_v">Email is required.</span>
            <span class="text-danger validation-ok password_v">Password must be at least 6 characters long.</span>
          </div>
        </div>                
      </div>
      <div class="modal-footer">
        <% if include_login_link==true %>
          <a class="btn black text-decoration-underline" id="already_have_an_account">I already have an account</a>
        <% else %>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>  
        <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/pages/_species_people_rankings.html.erb
<div class="row justify-content-center">
  <div class="col-5">
    <div class="row mt-5">
      <div class="col mb-3 h4 text-center proxima section-header">Top Species</div> 
    </div>  
    <div class="row my-5">
      <div class="col">
        <% object.get_top_species(10).each.with_index(1) do |s,i| %>
          <%= render partial: 'ranked_object', locals: { object: s, i: i } %>
        <% end %>
        <div class="row mt-2">
          <div class="col d-flex justify-content-end">
            <a data-bs-toggle="modal" data-bs-target="#species_modal" class="region-title-link" role="button">View All</a>
          </div>  
        </div>
      </div>  
    </div>
  </div>
  <div class="col"></div>
  <div class="col-5">
    <div class="row mt-5">
      <div class="col mb-3 h4 text-center proxima section-header">Top Observers</div> 
    </div>  
    <div class="row my-5">
      <div class="col">      
        <% object.get_top_people(10).each.with_index(1) do |p,i| %>
          <%= render partial: 'ranked_observer', locals: { object: p, i: i } %>
        <% end %>
        <div class="row mt-2">
          <div class="col d-flex justify-content-end">
            <a data-bs-toggle="modal" data-bs-target="#people_modal" class="region-title-link" role="button">View All</a>
          </div>  
        </div>        
      </div>      
    </div>
  </div>
</div>

<div class="modal fade" id="species_modal" tabindex="-1">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h6 class="modal-title text-center proxima section-header">Top Species</h6>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center mb-5">
          <div class="col-8">
            <% object.get_top_species.each.with_index(1) do |s,i| %>
              <%= render partial: 'ranked_object', locals: { object: s, i: i } %>
            <% end %>
          </div>  
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="people_modal" tabindex="-1">
  <div class="modal-dialog modal-lg modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h6 class="modal-title text-center proxima section-header">Top People</h6>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="row justify-content-center mb-5">
          <div class="col-8">
            <% object.get_top_people.each.with_index(1) do |s,i| %>
              <%= render partial: 'ranked_observer', locals: { object: s, i: i } %>
            <% end %>
          </div>  
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/region_contest.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-lg-10 d-flex justify-content-center proxima section-header h2 fw-bold text-dark text-center mt-5">
    <a href="<%= @region.get_path %>" class="proxima section-header h2 fw-bold text-dark"><%= @region.name %></a>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-lg-10 d-flex justify-content-center section-header h5 text-dark text-center mt-5">
    participating in
  </div>
</div>


<div class="row justify-content-center">
  <div class="col-12 col-lg-10 d-flex justify-content-center text-center my-5">
    <a href="<%= @contest.get_path %>" class="proxima section-header h2 fw-bold text-dark"><%= @contest.title %></a>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-lg-10 d-flex justify-content-center fw-bold h6">
    For observations made between <%= @contest.starts_at.strftime '%Y/%m/%d' %> and <%= @contest.ends_at.strftime '%Y/%m/%d' %></div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-lg-10 d-flex justify-content-center fs-italic h6">  
    Submissions accepted up to <%= @contest.last_submission_accepted_at.strftime '%Y/%m/%d' %></div>
  </div>
</div>

<% if !@region.raw_polygon_json.blank? && @region.raw_polygon_json!='[]' %>
  <div class="row justify-content-center mt-5">
    <div class="col-10">
      <div class="row my-3">
        <div class="col" id="region-map" style="width:100%; height:400px;"></div>  
        <script>  
          var _polygon_json = <%= @region.raw_polygon_json.html_safe %>;
          var _observations_filename = "/observations/participation/<%= @region.participations.where(contest_id: @contest.id).first.id %>";
          var _subregions = [];
        </script>
      </div>
    </div>
  </div>
<% end %>

<%= render partial: 'region_details', locals: { object: @region } %>

<%= render partial: 'statistics', locals: { object: @region.participations.where(contest_id: @contest.id).first } %>

<%= render partial: 'species_people_rankings', locals: { object: @region.participations.where(contest_id: @contest.id).first } %>

<%= render partial: 'recent_observations', locals: { observations: @observations, api_parameters: "?contest_id=#{ @contest.id }&region_id=#{ @region.id }" } %>

app/views/pages/users.html.erb
<div class="row justify-content-center my-5">
  <div class="col-6 col-lg-4">
    <button type="button" class="btn btn-warning w-100" data-bs-toggle="modal" data-bs-target="#new_user">+ New User</button>
  </div>
</div>

<%= render partial: 'signup_modal', locals: { title: 'New User', button_text: 'Save', id: 'new_user', include_login_link: false } %>

<div class="row my-5">
  <div class="col-3 fw-bold">Organization Name</div>
  <div class="col-3 fw-bold">Email</div>
  <div class="col-2 fw-bold">Role</div>
  <div class="col-2 fw-bold">Status</div>
  <div class="col-2"></div>
</div>

<% @users.each do |u| %>
  <div class="row mb-3">
  	<div class="col-3"><%= u.organization_name %></a></div>
  	<div class="col-3"><%= u.email %></div>
  	<div class="col-2"><%= u.role %></div>
    <div class="col-2"><%= u.status %></div>
  	<div class="col-2">
      <a role="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#user<%= u.id %>_modal">Edit</a>
    </div>
  </div>
<% end %>

<% @users.each do |u| %>
  <%= render partial: 'profile_modal', locals: { title: 'Edit User', id: "user#{ u.id }_modal", include_logout_link: false, user: u } %>
<% end %>  